### ISSUE TITLE
Dependency issue - Error: Cannot find module 'inquirer'

### ISSUE THREAD

**Issue by marcysutton** [typings/generator-typings#126]
I tried running this generator and immediately ran into a dependency problem. I'm really surprised I'm the only one! I was able to keep going after running `npm install inquirer`.

```
yo typings some-repo
```

```
readline.js:925
            throw err;
            ^

Error: Cannot find module 'inquirer'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/marcysutton/Sites/Organization/some-module/node_modules/generator-typings/generators/app/index.js:5:18)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
```

**Comment by blakeembrey** [comment]
@unional P.S. Might be worth integrating something like https://www.npmjs.com/package/dependency-check to catch this.

**Comment by unional** [comment]
Thanks. That's kind of strange. inquirer is a dependency of `yeoman-generator`, not directly by `generator-typings`.
Maybe there are some changes to the latest `yeoman-generator`.

@marcysutton , do you see which version of `yeoman-generator` it installed?

**Comment by unional** [comment]
Ar, no~, it is in the code. Don't know what it is there. Releasing a new version

**Comment by unional** [comment]
Fixed in latest release.
